### ISSUE TITLE
redme.md Link to "Android Streaming Apps 🎶" not working

### ISSUE THREAD

**Issue by k3b** [MoonWalker440/Music-Megathread#1]
The current link is "https://github.com/MoonWalker440/Music-Megathread/tree/main#android-streaming-apps-" . in the toc the link is "https://github.com/MoonWalker440/Music-Megathread/tree/main#android-streaming-apps" (without the trailing "-") which does not exist

**Comment by MoonWalker440** [comment]
It's fixed... Kindly re-check 😊
