### ISSUE TITLE
Help me find Music Player which has these features

### ISSUE THREAD

**Issue by PSVLTT** [MoonWalker440/Music-Megathread#12]
Hello there,
I really love this collection.
But can you give me some advice, about a desktop software has these features?:

- Organize PC local music files and folders.
- Can show multi artwork types (Front, back, CD, artist....)
- Can show something like  [apple animated cover album](https://help.apple.com/itc/albummotionguide/en.lproj/static.html)
- Can simple edit tags
- Playcount system
- Scrobbing LastFM
- If can, ez host for android streaming (not really important)

Im curently using [Georgia-Reborn](https://github.com/TT-ReBORN/Georgia-ReBORN) theme for Foobar2000, but I want to try something new.

Hope can get the answer.

Thank you very much.

**Comment by spftware** [comment]
I've used [Harmonoid](https://github.com/harmonoid/harmonoid) not sure if it supports tagging but I use [mp3tag](https://www.mp3tag.de/en) anyway.

I just decided to use the stock Media Player included in Windows nowadays tho.

**Comment by PSVLTT** [comment]
Thank you @spftware I will try it.

**Comment by MoonWalker440** [comment]
Try MediaMonkey or MusicBee. I guess MusicBee is likely the best fit for your requirements

**Comment by PSVLTT** [comment]
> Try MediaMonkey or MusicBee. I guess MusicBee is likely the best fit for your requirements

Thank you. I tried both but can not find the "animated cover" like apple music. did I missed something :(

**Comment by MoonWalker440** [comment]
MusicBee does have a plugin that provides visual enhancements which can offer a similar experience to Apple's animated cover album. The plugin you're looking for is the [3DBee plugin](https://www.getmusicbee.com/addons/plugins/481/3dbee) . While it may not be exactly like Apple's animated cover album, it does provide a visually appealing way to browse your album covers.

**Comment by PSVLTT** [comment]
> MusicBee does have a plugin that provides visual enhancements which can offer a similar experience to Apple's animated cover album. The plugin you're looking for is the [3DBee plugin](https://www.getmusicbee.com/addons/plugins/481/3dbee) . While it may not be exactly like Apple's animated cover album, it does provide a visually appealing way to browse your album covers.

Oh, I will give it a try. Thank youuuu!
