### ISSUE TITLE
Suggestion to add Music Presence

### ISSUE THREAD

**Issue by ungive** [MoonWalker440/Music-Megathread#17]
I would like to suggest the addition of a tool I have made called "Music Presence".

Music Presence is a little tray application which shares what you are listening to to your friends on Discord by creating a status which accurately reflects what song is currently playing on your device (also known as Discord RPC or Rich Presence). This includes the title of the song, the artist, album and album cover and the current playback position, if the media player supports it.

My program is novel in two ways:

- Unlike other "Discord RPC" programs which usually just work with one particular media player or only in specific contexts, Music Presence works with *any* media player out of the box. It's a one-stop solution to sharing your currently playing song on Discord.
- Unlike any other program, Music Presence shows the correct cover image in your status *100% of the time*. This has never been achieved before in the way Music Presence does it. Usually other developers would upload the cover image *permanently* on a platform like Imgur or other image hosts, which would break soon in the future because this approach is unsustainable (for obvious reasons). Music Presence uses a purpose-designed server for this, which only temporarily stores cover images for only the time they are needed.
- In addition to all of this, Music Presence is very customisable and the future is bright with a long roadmap of planned features ahead.

Future-proof URL (preferred for linking to): **https://musicpresence.app**
Repository: https://github.com/ungive/discord-music-presence
GitHub Organization: https://github.com/music-presence
Reddit post I made some time ago: https://www.reddit.com/r/TIdaL/comments/1d6azbm
Discord server: https://discord.com/invite/7rc8dWD4ug
Patreon: https://www.patreon.com/musicpresence

The domain in the first link currently points to the GitHub repository, but will soon link to a real website for the project. You can verify that the domain is really owned by me (the owner of the project) by checking the "Verified" badge in the GitHub organization I linked to above (this badge only shows if the domain that is visible there is verified via DNS records).

You can find further links in the README of the project.

While I couldn't find any fitting category in your list of tools so far, I think Music Presence is a worthy addition nevertheless, as people might come looking here for how to show their listening activity in their Discord status, as Discord is very popular these days and Discord only shows your listening activity if you are a Spotify user.

If you have any questions, I am happy to answer them.

Cheers!

---

![banner](https://github.com/user-attachments/assets/efb9e418-3eed-42ec-b7db-850c0d9900db)

**Comment by ungive** [comment]
If you were to add it but don't know how to advertise it in one sentence, here is a suggestion:

> *Share music from any media player in your Discord status: The missing counterpart to Spotify's exclusive "Listening to" status*

**Comment by Burhanverse** [comment]
@ungive Hmm interesting but it's limited to PC only I was wondering if it's possible to make it work on Android 🤔

**Comment by ungive** [comment]
@Burhanverse There's no mobile app for Music Presence at this time, you're right. I don't have plans for making one in the near future, as I'm focusing on different features, but there's apps like Kizzy which might do what you're looking for. Beware though, as all Android apps use the Discord API/Gateway, which is against Discord's ToS afaik. Discord RPC/Game SDK does not work in Android iirc.
