### ISSUE TITLE
Maybe add Rune Player

### ISSUE THREAD

**Issue by Losses** [MoonWalker440/Music-Megathread#19]
Rune Player is a music player that offers audio analysis and recommendation features. It introduces a new, modern music management paradigm to enhance your experience with cross-platform support and Fluent Design.

https://github.com/Losses/rune

https://github.com/user-attachments/assets/f363ff5e-d8e5-49b1-81f1-74efa831f83a

**Comment by MoonWalker440** [comment]
Got it. Added
